# Generated by Django 5.0.4 on 2024-04-17 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='cart',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seller.food'),
        ),
    ]
